[project]
name = "browser-sandbox"
version = "0.1.0"
description = "a browser sandbox service"
authors = [
  {name = "breadbread1984", email = "yxie.lhi@gmail.com"}
]
requires-python = ">=3.12"

dependencies = [
  "gradio",
  "absl-py",
  "fastapi",
  "uvicorn",
  "playwright"
]

